// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Viob_soc_sim__pch.h"
#include "Viob_soc_sim.h"
#include "Viob_soc_sim___024root.h"
#include "Viob_soc_sim_iob_soc_axi_full_xbar_split__pi2.h"
#include "Viob_soc_sim_iob_soc_axi_full_xbar_merge__pi3.h"
#include "Viob_soc_sim_ibex_core__pi4.h"
#include "Viob_soc_sim_prim_onehot_mux__W27_I20.h"

void Viob_soc_sim_ibex_core__pi4____Vdpiexp_if_stage_i__DOT__gen_prefetch_buffer__DOT__simutil_get_scramble_key_TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_lockstep__DOT__u_ibex_lockstep__DOT__u_shadow_core(Viob_soc_sim__Syms* __restrict vlSymsp, VlWide<4>/*127:0*/ &val, IData/*31:0*/ &simutil_get_scramble_key__Vfuncrtn);
void Viob_soc_sim_ibex_core__pi4____Vdpiexp_if_stage_i__DOT__gen_prefetch_buffer__DOT__simutil_get_scramble_nonce_TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_lockstep__DOT__u_ibex_lockstep__DOT__u_shadow_core(Viob_soc_sim__Syms* __restrict vlSymsp, VlWide<10>/*319:0*/ &nonce, IData/*31:0*/ &simutil_get_scramble_nonce__Vfuncrtn);
void Viob_soc_sim_ibex_core__pi4____Vdpiexp_if_stage_i__DOT__gen_prefetch_buffer__DOT__simutil_get_scramble_key_TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__u_ibex_core(Viob_soc_sim__Syms* __restrict vlSymsp, VlWide<4>/*127:0*/ &val, IData/*31:0*/ &simutil_get_scramble_key__Vfuncrtn);
void Viob_soc_sim_ibex_core__pi4____Vdpiexp_if_stage_i__DOT__gen_prefetch_buffer__DOT__simutil_get_scramble_nonce_TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__u_ibex_core(Viob_soc_sim__Syms* __restrict vlSymsp, VlWide<10>/*319:0*/ &nonce, IData/*31:0*/ &simutil_get_scramble_nonce__Vfuncrtn);

// FUNCTIONS
Viob_soc_sim__Syms::~Viob_soc_sim__Syms()
{
}

Viob_soc_sim__Syms::Viob_soc_sim__Syms(VerilatedContext* contextp, const char* namep, Viob_soc_sim* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_lockstep__DOT__u_ibex_lockstep__DOT__u_shadow_core{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.cpu.u_top.gen_lockstep.u_ibex_lockstep.u_shadow_core")}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_regfile_ff__DOT__register_file_i__DOT__gen_rdata_mux_check__DOT__u_rdata_a_mux{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.cpu.u_top.gen_regfile_ff.register_file_i.gen_rdata_mux_check.u_rdata_a_mux")}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_regfile_ff__DOT__register_file_i__DOT__gen_rdata_mux_check__DOT__u_rdata_b_mux{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.cpu.u_top.gen_regfile_ff.register_file_i.gen_rdata_mux_check.u_rdata_b_mux")}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__u_ibex_core{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.cpu.u_top.u_ibex_core")}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_0{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.iob_axi_full_xbar.iob_axi_merge_0")}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_1{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.iob_axi_full_xbar.iob_axi_merge_1")}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_2{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.iob_axi_full_xbar.iob_axi_merge_2")}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_split_0{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.iob_axi_full_xbar.iob_axi_split_0")}
    , TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_split_1{this, Verilated::catName(namep, "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.iob_axi_full_xbar.iob_axi_split_1")}
{
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_lockstep__DOT__u_ibex_lockstep__DOT__u_shadow_core = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_lockstep__DOT__u_ibex_lockstep__DOT__u_shadow_core;
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_regfile_ff__DOT__register_file_i__DOT__gen_rdata_mux_check__DOT__u_rdata_a_mux = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_regfile_ff__DOT__register_file_i__DOT__gen_rdata_mux_check__DOT__u_rdata_a_mux;
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_regfile_ff__DOT__register_file_i__DOT__gen_rdata_mux_check__DOT__u_rdata_b_mux = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_regfile_ff__DOT__register_file_i__DOT__gen_rdata_mux_check__DOT__u_rdata_b_mux;
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__u_ibex_core = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__u_ibex_core;
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_0 = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_0;
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_1 = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_1;
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_2 = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_2;
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_split_0 = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_split_0;
    TOP.__PVT__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_split_1 = &TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_split_1;
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_lockstep__DOT__u_ibex_lockstep__DOT__u_shadow_core.__Vconfigure(true);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_regfile_ff__DOT__register_file_i__DOT__gen_rdata_mux_check__DOT__u_rdata_a_mux.__Vconfigure(true);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_regfile_ff__DOT__register_file_i__DOT__gen_rdata_mux_check__DOT__u_rdata_b_mux.__Vconfigure(false);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__u_ibex_core.__Vconfigure(false);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_0.__Vconfigure(true);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_1.__Vconfigure(false);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_merge_2.__Vconfigure(false);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_split_0.__Vconfigure(true);
    TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__iob_axi_full_xbar__DOT__iob_axi_split_1.__Vconfigure(false);
    // Setup scopes
    __Vscope_iob_soc_sim__iob_soc_memwrapper__iob_core_inst__cpu__u_top__gen_lockstep__u_ibex_lockstep__u_shadow_core__if_stage_i.configure(this, name(), "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.cpu.u_top.gen_lockstep.u_ibex_lockstep.u_shadow_core.if_stage_i", "if_stage_i", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_iob_soc_sim__iob_soc_memwrapper__iob_core_inst__cpu__u_top__u_ibex_core__if_stage_i.configure(this, name(), "iob_soc_sim.iob_soc_memwrapper.iob_core_inst.cpu.u_top.u_ibex_core.if_stage_i", "if_stage_i", -9, VerilatedScope::SCOPE_OTHER);
    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_iob_soc_sim__iob_soc_memwrapper__iob_core_inst__cpu__u_top__gen_lockstep__u_ibex_lockstep__u_shadow_core__if_stage_i.exportInsert(__Vfinal, "simutil_get_scramble_key", (void*)(&Viob_soc_sim_ibex_core__pi4____Vdpiexp_if_stage_i__DOT__gen_prefetch_buffer__DOT__simutil_get_scramble_key_TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_lockstep__DOT__u_ibex_lockstep__DOT__u_shadow_core));
        __Vscope_iob_soc_sim__iob_soc_memwrapper__iob_core_inst__cpu__u_top__gen_lockstep__u_ibex_lockstep__u_shadow_core__if_stage_i.exportInsert(__Vfinal, "simutil_get_scramble_nonce", (void*)(&Viob_soc_sim_ibex_core__pi4____Vdpiexp_if_stage_i__DOT__gen_prefetch_buffer__DOT__simutil_get_scramble_nonce_TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__gen_lockstep__DOT__u_ibex_lockstep__DOT__u_shadow_core));
        __Vscope_iob_soc_sim__iob_soc_memwrapper__iob_core_inst__cpu__u_top__u_ibex_core__if_stage_i.exportInsert(__Vfinal, "simutil_get_scramble_key", (void*)(&Viob_soc_sim_ibex_core__pi4____Vdpiexp_if_stage_i__DOT__gen_prefetch_buffer__DOT__simutil_get_scramble_key_TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__u_ibex_core));
        __Vscope_iob_soc_sim__iob_soc_memwrapper__iob_core_inst__cpu__u_top__u_ibex_core__if_stage_i.exportInsert(__Vfinal, "simutil_get_scramble_nonce", (void*)(&Viob_soc_sim_ibex_core__pi4____Vdpiexp_if_stage_i__DOT__gen_prefetch_buffer__DOT__simutil_get_scramble_nonce_TOP__iob_soc_sim__DOT__iob_soc_memwrapper__DOT__iob_core_inst__DOT__cpu__DOT__u_top__DOT__u_ibex_core));
    }
}
